! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Parameters.f90
! Time                 : Fri Jul 11 18:25:47 2014
! Working directory    : /Research/GCAP2/KPP.ICECAP
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Parameters

  USE gckpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 170 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 160 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 125 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 10 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 506 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 161 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1647 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 2020 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 161 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 507 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 1498 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 170 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_DRYACET = 1 
  INTEGER, PARAMETER :: ind_DRYCH2O = 2 
  INTEGER, PARAMETER :: ind_DRYH2O2 = 3 
  INTEGER, PARAMETER :: ind_DRYHNO3 = 4 
  INTEGER, PARAMETER :: ind_DRYN2O5 = 5 
  INTEGER, PARAMETER :: ind_DRYNO2 = 6 
  INTEGER, PARAMETER :: ind_DRYO3 = 7 
  INTEGER, PARAMETER :: ind_DRYPAN = 8 
  INTEGER, PARAMETER :: ind_DRYPMN = 9 
  INTEGER, PARAMETER :: ind_DRYPMNN = 10 
  INTEGER, PARAMETER :: ind_DRYPPN = 11 
  INTEGER, PARAMETER :: ind_DRYR4N2 = 12 
  INTEGER, PARAMETER :: ind_DRYMVK = 13 
  INTEGER, PARAMETER :: ind_DRYMACR = 14 
  INTEGER, PARAMETER :: ind_DRYHAC = 15 
  INTEGER, PARAMETER :: ind_DRYALD2 = 16 
  INTEGER, PARAMETER :: ind_MSA = 17 
  INTEGER, PARAMETER :: ind_LISOPOH = 18 
  INTEGER, PARAMETER :: ind_DRYHOBr = 19 
  INTEGER, PARAMETER :: ind_DRYHBr = 20 
  INTEGER, PARAMETER :: ind_DRYBrNO3 = 21 
  INTEGER, PARAMETER :: ind_DRYBr2 = 22 
  INTEGER, PARAMETER :: ind_PYAC = 23 
  INTEGER, PARAMETER :: ind_DRYISOPND = 24 
  INTEGER, PARAMETER :: ind_DRYISOPNB = 25 
  INTEGER, PARAMETER :: ind_DRYRIP = 26 
  INTEGER, PARAMETER :: ind_DRYIEPOX = 27 
  INTEGER, PARAMETER :: ind_DRYMACRN = 28 
  INTEGER, PARAMETER :: ind_DRYMVKN = 29 
  INTEGER, PARAMETER :: ind_DRYPROPNN = 30 
  INTEGER, PARAMETER :: ind_DRYHCOOH = 31 
  INTEGER, PARAMETER :: ind_DRYACTA = 32 
  INTEGER, PARAMETER :: ind_DRYHCl = 33 
  INTEGER, PARAMETER :: ind_CO2 = 34 
  INTEGER, PARAMETER :: ind_DRYDEP = 35 
  INTEGER, PARAMETER :: ind_PPN = 36 
  INTEGER, PARAMETER :: ind_SO4 = 37 
  INTEGER, PARAMETER :: ind_BrNO2 = 38 
  INTEGER, PARAMETER :: ind_IEPOX = 39 
  INTEGER, PARAMETER :: ind_PMNN = 40 
  INTEGER, PARAMETER :: ind_N2O = 41 
  INTEGER, PARAMETER :: ind_N = 42 
  INTEGER, PARAMETER :: ind_PAN = 43 
  INTEGER, PARAMETER :: ind_OCS = 44 
  INTEGER, PARAMETER :: ind_SO2 = 45 
  INTEGER, PARAMETER :: ind_ALK4 = 46 
  INTEGER, PARAMETER :: ind_MAP = 47 
  INTEGER, PARAMETER :: ind_CHBr3 = 48 
  INTEGER, PARAMETER :: ind_CH2Br2 = 49 
  INTEGER, PARAMETER :: ind_MPN = 50 
  INTEGER, PARAMETER :: ind_Cl2O2 = 51 
  INTEGER, PARAMETER :: ind_RA3P = 52 
  INTEGER, PARAMETER :: ind_RB3P = 53 
  INTEGER, PARAMETER :: ind_DMS = 54 
  INTEGER, PARAMETER :: ind_OClO = 55 
  INTEGER, PARAMETER :: ind_ClNO2 = 56 
  INTEGER, PARAMETER :: ind_C3H8 = 57 
  INTEGER, PARAMETER :: ind_ETP = 58 
  INTEGER, PARAMETER :: ind_HNO2 = 59 
  INTEGER, PARAMETER :: ind_CH3Br = 60 
  INTEGER, PARAMETER :: ind_CH3Cl = 61 
  INTEGER, PARAMETER :: ind_MAOP = 62 
  INTEGER, PARAMETER :: ind_MP = 63 
  INTEGER, PARAMETER :: ind_ClOO = 64 
  INTEGER, PARAMETER :: ind_HNO4 = 65 
  INTEGER, PARAMETER :: ind_RP = 66 
  INTEGER, PARAMETER :: ind_BrCl = 67 
  INTEGER, PARAMETER :: ind_Br2 = 68 
  INTEGER, PARAMETER :: ind_ETHLN = 69 
  INTEGER, PARAMETER :: ind_PP = 70 
  INTEGER, PARAMETER :: ind_MRP = 71 
  INTEGER, PARAMETER :: ind_PRPN = 72 
  INTEGER, PARAMETER :: ind_R4P = 73 
  INTEGER, PARAMETER :: ind_RIP = 74 
  INTEGER, PARAMETER :: ind_VRP = 75 
  INTEGER, PARAMETER :: ind_ATOOH = 76 
  INTEGER, PARAMETER :: ind_C2H6 = 77 
  INTEGER, PARAMETER :: ind_IAP = 78 
  INTEGER, PARAMETER :: ind_DHMOB = 79 
  INTEGER, PARAMETER :: ind_MOBA = 80 
  INTEGER, PARAMETER :: ind_N2O5 = 81 
  INTEGER, PARAMETER :: ind_INPN = 82 
  INTEGER, PARAMETER :: ind_ISNP = 83 
  INTEGER, PARAMETER :: ind_ISOPNB = 84 
  INTEGER, PARAMETER :: ind_CH4 = 85 
  INTEGER, PARAMETER :: ind_H2O2 = 86 
  INTEGER, PARAMETER :: ind_IEPOXOO = 87 
  INTEGER, PARAMETER :: ind_MACRNO2 = 88 
  INTEGER, PARAMETER :: ind_PMN = 89 
  INTEGER, PARAMETER :: ind_MOBAOO = 90 
  INTEGER, PARAMETER :: ind_ROH = 91 
  INTEGER, PARAMETER :: ind_DIBOO = 92 
  INTEGER, PARAMETER :: ind_PRPE = 93 
  INTEGER, PARAMETER :: ind_MVKN = 94 
  INTEGER, PARAMETER :: ind_H = 95 
  INTEGER, PARAMETER :: ind_BrNO3 = 96 
  INTEGER, PARAMETER :: ind_Cl2 = 97 
  INTEGER, PARAMETER :: ind_ISNOHOO = 98 
  INTEGER, PARAMETER :: ind_ISOP = 99 
  INTEGER, PARAMETER :: ind_PROPNN = 100 
  INTEGER, PARAMETER :: ind_ISNOOB = 101 
  INTEGER, PARAMETER :: ind_HOBr = 102 
  INTEGER, PARAMETER :: ind_A3O2 = 103 
  INTEGER, PARAMETER :: ind_CO = 104 
  INTEGER, PARAMETER :: ind_GLYC = 105 
  INTEGER, PARAMETER :: ind_MACRN = 106 
  INTEGER, PARAMETER :: ind_ISOPND = 107 
  INTEGER, PARAMETER :: ind_MAOPO2 = 108 
  INTEGER, PARAMETER :: ind_MRO2 = 109 
  INTEGER, PARAMETER :: ind_ACET = 110 
  INTEGER, PARAMETER :: ind_HC5 = 111 
  INTEGER, PARAMETER :: ind_GLYX = 112 
  INTEGER, PARAMETER :: ind_VRO2 = 113 
  INTEGER, PARAMETER :: ind_ISNOOA = 114 
  INTEGER, PARAMETER :: ind_MAN2 = 115 
  INTEGER, PARAMETER :: ind_PO2 = 116 
  INTEGER, PARAMETER :: ind_PRN1 = 117 
  INTEGER, PARAMETER :: ind_MGLY = 118 
  INTEGER, PARAMETER :: ind_B3O2 = 119 
  INTEGER, PARAMETER :: ind_ETO2 = 120 
  INTEGER, PARAMETER :: ind_RCO3 = 121 
  INTEGER, PARAMETER :: ind_ClNO3 = 122 
  INTEGER, PARAMETER :: ind_KO2 = 123 
  INTEGER, PARAMETER :: ind_R4N1 = 124 
  INTEGER, PARAMETER :: ind_HOCl = 125 
  INTEGER, PARAMETER :: ind_ISN1 = 126 
  INTEGER, PARAMETER :: ind_HAC = 127 
  INTEGER, PARAMETER :: ind_HNO3 = 128 
  INTEGER, PARAMETER :: ind_ATO2 = 129 
  INTEGER, PARAMETER :: ind_MVK = 130 
  INTEGER, PARAMETER :: ind_HC5OO = 131 
  INTEGER, PARAMETER :: ind_RIO2 = 132 
  INTEGER, PARAMETER :: ind_MAO3 = 133 
  INTEGER, PARAMETER :: ind_INO2 = 134 
  INTEGER, PARAMETER :: ind_MACR = 135 
  INTEGER, PARAMETER :: ind_ISOPNBO2 = 136 
  INTEGER, PARAMETER :: ind_ISOPNDO2 = 137 
  INTEGER, PARAMETER :: ind_R4O2 = 138 
  INTEGER, PARAMETER :: ind_RCHO = 139 
  INTEGER, PARAMETER :: ind_MEK = 140 
  INTEGER, PARAMETER :: ind_R4N2 = 141 
  INTEGER, PARAMETER :: ind_MCO3 = 142 
  INTEGER, PARAMETER :: ind_ALD2 = 143 
  INTEGER, PARAMETER :: ind_CH2O = 144 
  INTEGER, PARAMETER :: ind_MO2 = 145 
  INTEGER, PARAMETER :: ind_NO = 146 
  INTEGER, PARAMETER :: ind_H2O = 147 
  INTEGER, PARAMETER :: ind_HO2 = 148 
  INTEGER, PARAMETER :: ind_ClO = 149 
  INTEGER, PARAMETER :: ind_NO3 = 150 
  INTEGER, PARAMETER :: ind_OH = 151 
  INTEGER, PARAMETER :: ind_O = 152 
  INTEGER, PARAMETER :: ind_Br = 153 
  INTEGER, PARAMETER :: ind_HBr = 154 
  INTEGER, PARAMETER :: ind_O1D = 155 
  INTEGER, PARAMETER :: ind_O3 = 156 
  INTEGER, PARAMETER :: ind_NO2 = 157 
  INTEGER, PARAMETER :: ind_HCl = 158 
  INTEGER, PARAMETER :: ind_BrO = 159 
  INTEGER, PARAMETER :: ind_Cl = 160 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_ACTA = 161 
  INTEGER, PARAMETER :: ind_EMISSION = 162 
  INTEGER, PARAMETER :: ind_EOH = 163 
  INTEGER, PARAMETER :: ind_H2 = 164 
  INTEGER, PARAMETER :: ind_HCOOH = 165 
  INTEGER, PARAMETER :: ind_MOH = 166 
  INTEGER, PARAMETER :: ind_N2 = 167 
  INTEGER, PARAMETER :: ind_O2 = 168 
  INTEGER, PARAMETER :: ind_RCOOH = 169 
  INTEGER, PARAMETER :: ind_DUMMY = 170 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_ACTA = 1 
  INTEGER, PARAMETER :: indf_EMISSION = 2 
  INTEGER, PARAMETER :: indf_EOH = 3 
  INTEGER, PARAMETER :: indf_H2 = 4 
  INTEGER, PARAMETER :: indf_HCOOH = 5 
  INTEGER, PARAMETER :: indf_MOH = 6 
  INTEGER, PARAMETER :: indf_N2 = 7 
  INTEGER, PARAMETER :: indf_O2 = 8 
  INTEGER, PARAMETER :: indf_RCOOH = 9 
  INTEGER, PARAMETER :: indf_DUMMY = 10 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 814 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 2105 

END MODULE gckpp_Parameters

